# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nepgen-ai

on:
  push:
    branches:
      - everest
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://nepgen.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7c8772c2cec24f42aa3e7e398add4b9f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4a28c0c55c22418884ed762dac9dae9e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: nepgen.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7c8772c2cec24f42aa3e7e398add4b9f }}/nepgen/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nepgen-ai'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fff020cb1ccf4b43ad96be35cf634574 }}
        images: 'nepgen.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7c8772c2cec24f42aa3e7e398add4b9f }}/nepgen/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'